project_id = "yflbjaetupvakadqjhfb"

[functions.query-open-beauty-facts]
verify_jwt = false

[functions.query-pubchem]
verify_jwt = false

[functions.analyze-product]
verify_jwt = true

[functions.optimize-routine]
verify_jwt = true