project_id = "yflbjaetupvakadqjhfb"

[functions.find-dupes]
verify_jwt = false

[functions.query-open-beauty-facts]
verify_jwt = false

[functions.query-pubchem]
verify_jwt = false

[functions.analyze-product]
verify_jwt = true

[functions.optimize-routine]
verify_jwt = true

[functions.chat-skinlytix]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true